### PR TITLE
string type + concat operator + str_contains function

### PR DESCRIPTION
**Pull request by solidpulse**
very initial implementation

contains:
- string type
- concat operator
- str_contains function https://wiki.php.net/rfc/str_contains

what doesn't work:
- string interpolation
- binary strings
- doesn't care about encoding

but should be enough to start implementing a lot of those PHP string functions.

### CODE REVIEW

**Comment by solidpulse** [comment]
@abertschi 
Those CodeFactor checks could be ignored I guess.
Let me know if I have gone awfully wrong 😅

**Comment by Girgias** [comment]
>     * binary strings
> 
>     * doesn't care about encoding
> 
PHP strings are also byte arrays therefore don't care about encodings, however this could be a problem to implement the str functions as they work on a byte level not on a "character"/grapheme

**Comment by abertschi** [comment]
> @abertschi
> Those CodeFactor checks could be ignored I guess.
> Let me know if I have gone awfully wrong sweat_smile


While I appreciate your efforts in contributing to this project, your submitted code is nowhere near where I could merge it into master. Implementing string functionality is rather involved. As you pointed out implicit and explicit casts must be supported and most nodes which currently support other data types such as integer must be extended to deal with strings.

I don't think re-implementing all string functions is very efficient in terms of time spent. I much rather would evaluate how standard library functions written by the Zend Engine project can be reused. See my answer [0].

I currently do not have much capacity to do mentoring. At the current point of your submitted code I much rather implement the functionality myself than mentor you through changes to achieve the desired functionality. I hope this gives you some feedback.

You may want to look through other issues and start with less involved tasks to contribute. But also there, the list and description of features is rather sparse.

[0] - https://github.com/abertschi/graalphp/issues/57#issuecomment-699504478

**Comment by abertschi** [comment]
If you want to get more familiar with Graal and Truffle, here is a useful compilation of resources:

- https://gist.github.com/smarr/d1f8f2101b5cc8e14e12 
- https://www.graalvm.org/community/publications/

**Comment by solidpulse** [comment]
> At the current point of your submitted code I much rather implement the functionality myself than mentor you through changes to achieve the desired functionality.

Yeah, this would be good learning for me to see and compare what I missed.

> But also there, the list and description of features is rather sparse.

You might want to expand on a few of these, I'll see what I can pick up myself as well.

Thanks @abertschi , might be a while before I am actually useful but hopefully soon 😄

**Pull request closed without merging**
